[Service]
Environment=LP_RPC_HEAD_URLS=http://127.0.0.1:8547
Environment=LP_RPC_HEAD_URL_FILES=%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_STATE_URL_FILES=%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_HISTORY_STATE_URLS=
Environment=LP_RPC_HISTORY_STATE_URL_FILES=%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_LOG_URLS=http://127.0.0.1:8547
Environment=LP_RPC_LOG_URL_FILES=%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_RECEIPT_URL_FILES=%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_DISABLE_TRACE=0
Environment=LP_RPC_TRACE_URL_FILES=%h/.config/robinhoodpools/goldsky.url
