[Service]
Environment=LP_RPC_HEAD_URLS=
Environment=LP_RPC_HEAD_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_STATE_URLS=
Environment=LP_RPC_STATE_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_HISTORY_STATE_URLS=
Environment=LP_RPC_HISTORY_STATE_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_LOG_URLS=
Environment=LP_RPC_LOG_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_RECEIPT_URLS=
Environment=LP_RPC_RECEIPT_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_TRACE_URLS=
Environment=LP_RPC_TRACE_URL_FILES=%h/.config/robinhoodpools/quicknode-http.urls,%h/.config/robinhoodpools/goldsky.url
Environment=LP_RPC_DISABLE_TRACE=0
Environment=LP_RPC_HEAD_WSS_URLS=
Environment=LP_RPC_HEAD_WSS_URL_FILES=%h/.config/robinhoodpools/quicknode-wss.urls
